default_platform(:ios)
skip_docs

platform :ios do
  before_all do
    setup_ci if ENV['CI']
  end

  desc "Test"
  lane :test do
    scan(
      package_path: './',
      destination: 'platform=iOS Simulator,name=iPhone 14 Pro',
      scheme: "GeoKit",
      code_coverage: true,
      result_bundle: true
    )
  end
end
